In [1]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('iris.csv')
df.head()
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import ComplementNB
x = df.drop(['Species'],axis = 1)
y = df['Species']
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.5,random_state = 0)
mnb = ComplementNB()
Y_pred = mnb.fit(X_train,Y_train).predict(X_test)
Y_pred

array(['Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
    

In [17]:
import sklearn.metrics
lbs = ['Iris-versicolor','Iris-setosa','Iris-virginica']
print(sklearn.metrics.confusion_matrix(Y_test,Y_pred,labels = lbs))
print(sklearn.metrics.accuracy_score(Y_test,Y_pred))
print(sklearn.metrics.precision_score(Y_test,Y_pred,labels = lbs,pos_label = 1,average = 'micro'))
print(sklearn.metrics.f1_score(Y_test,Y_pred,labels = lbs,pos_label = 1,average = 'micro'))
print(sklearn.metrics.recall_score(Y_test,Y_pred,labels = lbs,pos_label = 1,average = 'micro'))

[[ 0  7 23]
 [ 0 21  0]
 [ 0  0 24]]
0.6
0.6
0.6
0.6
