In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
df.shape

(150, 6)

In [23]:
df.columns = ["ID","sepallength","spealwidth","petallength","petalwidth","Species"]

In [25]:
# since the values lies in different ranger we use scaler to scale them
#Min Max Scaler

In [27]:
x = df.drop(['Species'],axis = 1)
y = df['Species']

In [33]:
min(x['sepallength'])

4.3

In [37]:
max(x['sepallength'])

7.9

In [39]:
min(x['petallength'])

1.0

In [41]:
max(x['petallength'])

6.9

In [43]:
min(x['petalwidth'])

0.1

In [45]:
max(x['petalwidth'])

2.5

In [49]:
from sklearn.preprocessing import MinMaxScaler

In [53]:
scalar = MinMaxScaler()
x_scaled = scalar.fit_transform(x)
x_scaled

array([[0.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.00671141, 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.01342282, 0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.02013423, 0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.02684564, 0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.03355705, 0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.04026846, 0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.04697987, 0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.05369128, 0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.06040268, 0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.06711409, 0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.0738255 , 0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.08053691, 0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.08724832, 0.        , 0.41666667, 0.01694915, 0.        ],
       [0.09395973, 0.41666667, 0.

In [57]:
from sklearn.model_selection import train_test_split

In [59]:
X_train,X_test,Y_train,Y_test = train_test_split(x_scaled,y,test_size = 0.5,random_state = 42)

In [61]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,Y_train)

GaussianNB()

In [63]:
Y_pred = gnb.predict(X_test)

In [65]:
Y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',


In [67]:
Y_test

73     Iris-versicolor
18         Iris-setosa
118     Iris-virginica
78     Iris-versicolor
76     Iris-versicolor
            ...       
113     Iris-virginica
33         Iris-setosa
138     Iris-virginica
101     Iris-virginica
62     Iris-versicolor
Name: Species, Length: 75, dtype: object

In [71]:
from sklearn import metrics

In [85]:
import sklearn.metrics
lbs = ['Iris-versicolor','Iris-setosa','Iris-virginica']
print(sklearn.metrics.confusion_matrix(Y_test,Y_pred,labels = lbs))
print(sklearn.metrics.accuracy_score(Y_test,Y_pred))
print(sklearn.metrics.precision_score(Y_test,Y_pred,labels = lbs,pos_label = 1,average = 'micro'))
print(sklearn.metrics.f1_score(Y_test,Y_pred,labels = lbs,pos_label = 1,average = 'micro'))
print(sklearn.metrics.recall_score(Y_test,Y_pred,labels = lbs,pos_label = 1,average = 'micro'))

[[23  0  0]
 [ 0 29  0]
 [ 0  0 23]]
1.0
1.0
1.0
1.0
